---
- name: Install Webcam Settings via Mac App Store
  command: mas install "{{ item.id }}"
  args:
    creates: /Applications/{{ item.name }}.app
  with_items:
    - { id: 533696630, name: "Webcam Settings" }
  when: ansible_os_family == "Darwin"
